# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sqsgh6aCcARuma97fwhshD2UIEarb6qZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

start ='2012-01-01'
end ='2022-12-01'
stock = 'GOOG'

data = yf.download(stock,start,end)

data.reset_index(inplace=True)

data

plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data['Close'], label='Closing Price')
plt.plot(data['Date'], data['30_day_MA'], label='10 years Moving Average', color='red')
plt.title('Closing Price and 10 years Moving Average Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.xticks(rotation=50)
plt.tight_layout()
plt.show()

data_for_plot = data[['Date', 'Close']]
data_for_plot.columns = ['Date', 'Close']
data_for_plot.head()

plt.figure(figsize=(10,6))
plt.plot(data_for_plot['Date'], data_for_plot['Close'])
plt.title('Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

data['30_day_MA'] = data['Close'].rolling(window=30).mean()
display(data.head())

data